[package]
name = "ceos"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0.89"
eframe = "0.33"
egui = "0.33"
egui_extras = "0.33"
egui_solarized = "0.33"
env_logger = "0.11"
humansize = "2.1.3"
log = "0.4"
logos = "0.15"
rfd = "0.15.0"
rstest = "0.26"